encoder-embed-dim-subtransformer: 512
decoder-embed-dim-subtransformer: 512

encoder-ffn-embed-dim-all-subtransformer: [1024, 3072, 3072, 2048, 3072, 2048]
decoder-ffn-embed-dim-all-subtransformer: [1024, 1024, 2048]

encoder-layer-num-subtransformer: 6
decoder-layer-num-subtransformer: 3

encoder-self-attention-heads-all-subtransformer: [8, 8, 8, 8, 8, 8]
decoder-self-attention-heads-all-subtransformer: [4, 8, 8]
decoder-ende-attention-heads-all-subtransformer: [8, 8, 8]

decoder-arbitrary-ende-attn-all-subtransformer: [1, 1, -1]

